annietribe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),

                  # orders urls
                  path('payment/', include('payment.urls', namespace='payment')),

                  # orders urls
                  path('orders/', include('orders.urls', namespace='orders')),

                  # coupon urls
                  path('coupons/', include('coupons.urls', namespace='coupons')),

                  # cart urls
                  path('cart/', include('cart.urls', namespace='cart')),

                  # wishlist urls
                  path('wishlist/', include('wishlist.urls', namespace='wishlist')),

                  # account
                  path('account/', include('account.urls', namespace='account')),

                  # products
                  path('', include('products.urls', namespace='products')),

                  # ckeditor
                  path('ckeditor/', include('ckeditor_uploader.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

payment/urls.py
from django.urls import path, include
from . import views

app_name = 'payment'

urlpatterns = [
    path('payment_options/', views.payment_options, name='payment_options'),

    path('card_payment/', views.card_payment, name='card_payment'),

    path('access/token', views.get_access_token, name='get_mpesa_access_token'),

    path('mpesa_payment/', views.mpesa_payment, name='mpesa_payment'),

    # register, confirmation, validation and callback urls
    path('register_mpesa_validation/', views.register_urls, name="register_mpesa_validation"),
    path('confirmation/', views.confirmation, name="confirmation"),
    path('validation/', views.validation, name="validation"),
    path('callback/', views.call_back, name="call_back"),

    path('payment_done/', views.payment_done, name='payment_done'),

    path('payment_canceled', views.payment_canceled, name='payment_canceled'),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [
    # newsletter urls
    path('subscribe', views.subscribe_view, name='subscribe'),

    path('success/', views.subscribe_success_view, name='subscribe_success'),

    path('fail/', views.subscribe_fail_view, name='subscribe_fail'),

    path('unsubscribe/', views.unsubscribe_view, name='unsubscribe'),

    path('unsubscribe/success/', views.unsubscribe_success_view, name='unsubscribe_success'),

    path('unsubscribe/fail/', views.unsubscribe_fail_view, name='unsubscribe_fail'),

    # index page
    path('', views.index, name='index'),

    path('contact/', views.contact, name='contact'),

    # list of all products
    path('products/', views.product_list, name='product_list'),

    path('search/', views.search, name='search'),

    # list of products in a given category
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),

    # product detail
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

payment/models.py
from django.db import models


# Create your models here.
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# M-pesa Payment models
class MpesaCalls(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()

    class Meta:
        verbose_name = 'Mpesa Call'
        verbose_name_plural = 'Mpesa Calls'


class MpesaCallBacks(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()

    class Meta:
        verbose_name = 'Mpesa Call Back'
        verbose_name_plural = 'Mpesa Call Backs'


class MpesaPayment(BaseModel):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    type = models.TextField()
    reference = models.TextField()
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.TextField()
    organization_balance = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'

    def __str__(self):
        return self.first_name

payment/forms.py
from django import forms


class MpesaPhoneForm(forms.Form):
    phone = forms.CharField(help_text='format: 254 742 XXX XXX')

payment/views.py
import json
import requests
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from orders.models import OrderItem, Order
from .forms import MpesaPhoneForm
from .models import MpesaPayment

from .mpesa_credentials import MpesaAccessToken, LipanaMpesaPpassword
import braintree
from requests.auth import HTTPBasicAuth

# Create your views here.
# instantiating braintree payment gateway

gateway = braintree.BraintreeGateway(settings.BRAINTREE_CONF)


@login_required
def payment_options(request):
    order_id = request.session.get('order_id')
    order = Order.objects.get(id=order_id)
    ordered_items = OrderItem.objects.filter(order=order_id)

    return render(request, 'payment_options.html',
                  {'order': order,
                   'ordered_items': ordered_items})


@login_required
def card_payment(request):
    order_id = request.session.get('order_id')
    order = Order.objects.get(id=order_id)
    ordered_items = OrderItem.objects.filter(order=order_id)
    total_cost_after_discount = order.get_total_cost_after_discount()

    if request.method == 'POST':
        # retrieve nonce
        nonce = request.POST.get('payment_method_nonce', None)

        # create and submit transaction
        result = gateway.transaction.sale({
            'amount': f'{total_cost_after_discount:.2f}',
            'payment_method_nonce': nonce,
            'options': {'submit_for_settlement': True}
        })

        if result.is_success:
            # mark the order as paid
            order.paid = True
            # store unique transaction id
            order.braintree_id = result.transaction.id
            order.save()

            return redirect('payment:payment_done')
        else:
            return redirect('payment:payment_canceled')
    else:
        # generate token
        client_token = gateway.client_token.generate()

    return render(request, 'card.html',
                  {'order': order,
                   'ordered_items': ordered_items,
                   'total_cost_after_discount': total_cost_after_discount,
                   'client_token': client_token})


@login_required
def get_access_token(request):
    consumer_key = 'E4yc9wFcaAdeoFe2vxYVzSAT7M2nroQU'
    consumer_secret = 'uWsn21FgMbIzhmE3'

    # url for generating mpesa token
    api_url = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'

    # initiate http call to mpesa sandbox
    r = requests.get(api_url, auth=HTTPBasicAuth(consumer_key, consumer_secret))

    # parsing the json string from safaricom
    mpesa_access_token = json.loads(r.text)

    # accessing the mpesa token
    validated_mpesa_access_token = mpesa_access_token['access_token']

    return HttpResponse(validated_mpesa_access_token)


@login_required
def mpesa_payment(request):
    # retrieve the current order
    order_id = request.session.get('order_id')
    order = Order.objects.get(id=order_id)
    ordered_items = OrderItem.objects.filter(order=order_id)
    total_cost_after_discount = order.get_total_cost_after_discount()

    if request.method == 'POST':
        phone = request.POST.get('phone')

        # converting to float and str to make the objects JSON serializable
        total_cost_after_discount = int(total_cost_after_discount)

        access_token = MpesaAccessToken.validated_mpesa_access_token
        api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"

        headers = {"Authorization": "Bearer %s" % access_token}

        request = {
            "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,  # paybill or buy goods till number
            "Password": LipanaMpesaPpassword.decode_password,  # password used to encrypt the requests sent
            "Timestamp": LipanaMpesaPpassword.lipa_time,  # transaction timestamp
            "TransactionType": "CustomerPayBillOnline",  # used to identify the type of transaction
            "Amount": float(total_cost_after_discount),  # the amount you intend to pay
            "PartyA": phone,  # phone number sending the money
            "PartyB": LipanaMpesaPpassword.Business_short_code,  # organization receiving the funds can also be
            # BusinesShortCode
            "PhoneNumber": phone,  # number to receive the STK pin Prompt. can be same as PartA
            "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",  # valid secure url used to receive notifications
            # from mpesa api. it is the endpoint to which the results will be sent by the mpesa api
            "AccountReference": "Annie Tribe",  # the name of the business
            "TransactionDesc": "Testing stk push"
            # additional information that that can be sent along with the sys's req
        }

        response = requests.post(api_url, json=request, headers=headers)

        order.paid = True
        order.save()
        return redirect('payment:payment_done')
    else:
        form = MpesaPhoneForm()
        return render(request, 'mpesa.html',
                      {'order': order,
                       'ordered_items': ordered_items,
                       'total_cost_after_discount': total_cost_after_discount,
                       'form': form})




@csrf_exempt
def register_urls(request):  # use this method to register our confirmation and validation URL with Safaricom.
    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
    headers = {"Authorization": "Bearer %s" % access_token}
    options = {"ShortCode": LipanaMpesaPpassword.Test_c2b_shortcodee,
               "ResponseType": "Completed",
               "ConfirmationURL": "https://0bd7-154-159-237-225.in.ngrok.io/payment/confirmation/",
               "ValidationURL": "https://0bd7-154-159-237-225.in.ngrok.io/payment/validation/"}
    response = requests.post(api_url, json=options, headers=headers)
    return HttpResponse(response.text)


@csrf_exempt
def call_back(request):
    pass


@csrf_exempt
def validation(request):
    context = {
        "ResultCode": 0,
        "ResultDesc": "Accepted"
    }
    return JsonResponse(dict(context))


@csrf_exempt
def confirmation(request):
    mpesa_body = request.body.decode('utf-8')
    mpesa_payment = json.loads(mpesa_body)
    payment = MpesaPayment(
        first_name=mpesa_payment['FirstName'],
        last_name=mpesa_payment['LastName'],
        middle_name=mpesa_payment['MiddleName'],
        description=mpesa_payment['TransID'],
        phone_number=mpesa_payment['MSISDN'],
        amount=mpesa_payment['TransAmount'],
        reference=mpesa_payment['BillRefNumber'],
        organization_balance=mpesa_payment['OrgAccountBalance'],
        type=mpesa_payment['TransactionType'],
    )
    payment.save()
    context = {
        "ResultCode": 0,
        "ResultDesc": "Accepted"
    }
    return JsonResponse(dict(context))


@login_required
def payment_done(request):
    return render(request, 'payment_done.html')


@login_required
def payment_canceled(request):
    return render(request, 'payment_canceled.html')

payment/templates/card.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Card Payment
{% endblock %}

{% block content %}

<style>
#card-number, #expiration-date, #cvv{
        border: 1px solid black;
        height: 32px;
        padding: 1px;
    }
</style>

    <!-- Visa and Master Card Payment -->

    <div class="mt-2 pt-3 pb-3 container mx-auto">

      <div class="row gx-4 gy-2 justify-content-center">
        <div class="col-lg-6 col-md-6 col-sm-6">
          <div class="order_summary p-2">
            <h3 class="fw-bold">Order Summary</h3>

            {% for item in ordered_items %}
            <div class="products">
              <p class="d-inline">
                <span class="fw-bold"> 1X </span>
               {{ item.product.name }}
              </p>

              <span class="float-end d-inline fw-bold">KES: {{ item.product.price }}</span>
            </div>
            {% endfor %}


            <h6 class="fw-bold text-end mt-4">Sub-Total: {{ order.get_total_cost }}</h6>

           {% if order.coupon %}
               <h6 class="fw-bold text-muted text-end">Coupon: <span class="text-danger">{{ order.discount }}% discount</span></h6>
            {% endif %}
            <hr class="text-danger">
            <h5 class="fw-bold text-end">Total: KES: {{ order.get_total_cost_after_discount }}</h5>
            <hr class="text-danger">

            <p class="text-center fw-bold fst-italic text-muted">Please note that delivery fees is not included!!</p>
          </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6 text-center">

          <div class="order_summary p-2">
            <h3 class="fw-bold">Visa or Master Card</h3>

            <div class="card border-0">
              <img src="{% static 'images/card.png' %}" class="card-img-top w-25 mx-auto" alt="card image">
              <div class="card-body">

                <form id="payment" method="post">

                  <label for="card-number" class="fw-bold">Card Number</label>
                        <div id="card-number" class="field rounded"></div>

                        <label for="cvv" class="fw-bold">CVV</label>
                        <div id="cvv" class="field rounded"></div>

                        <label for="expiration-date" class="fw-bold">Expiration Date</label>
                        <div id="expiration-date" class="field rounded"></div>

                        <input type="hidden" id="nonce" name="payment_method_nonce" value="">
                        {% csrf_token %}
                  <input type="submit" value="PAY NOW: KES: {{ total_cost_after_discount }}" class="btn btn-dark btn-outline-light fw-bold mt-2">
                </form>

              </div>
            </div>



          </div>


        </div>
      </div>


      <div class="d-flex">
        <a href="{% url 'payment:payment_options' %}" class="mt-2 btn btn-dark btn-outline-light fw-bold mx-auto">
          <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
          Payment Options
        </a>


       <!-- <a href="order.html" class="mt-2 btn btn-dark btn-outline-danger fw-bold mx-auto flex-end">
          Proceed
          <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
        </a> -->

      </div>

    </div>

    <!-- includes the Braintree JS client SDK -->
    <script src="https://js.braintreegateway.com/web/3.58.0/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.58.0/js/hosted-fields.min.js"></script>
    <script>
      var form = document.querySelector('#payment');
      var submit = document.querySelector('input[type="submit"]');

      braintree.client.create({
        authorization: '{{ client_token }}'
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {'font-size': '13px'},
            'input.invalid': {'color': 'red'},
            'input.valid': {'color': 'green'}
          },
          fields: {
            number: {selector: '#card-number'},
            cvv: {selector: '#cvv'},
            expirationDate: {selector: '#expiration-date'}
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }
              // set nonce to send to the server
              document.getElementById('nonce').value = payload.nonce;
              // submit form
              document.getElementById('payment').submit();
            });
          }, false);
        });
      });
    </script>

{% endblock %}

payment/templates/mpesa.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Mpesa Payment
{% endblock %}

{% block content %}

<style>
    #div_id_phone{
        color: red;
    {
</style>

    <!-- Payment Options -->

    <div class="mt-2 pt-3 pb-3 container mx-auto">

      <div class="row gx-4 gy-2 justify-content-center">
        <div class="col-lg-6 col-md-6 col-sm-6 text-center">

          <div class="order_summary p-2">
            <h2 class="fw-bold">Lipa na Mpesa</h2>

            <div class="card border-0">
              <img src="{% static 'images/mpesa.png' %}" class="card-img-top w-25 mx-auto" alt="...">
              <div class="card-body">

                <form method="post">
                    <p class="fw-bold">Enter a valid Safaricom Number:</p>
                    {% csrf_token %}
                    {{ form.phone|as_crispy_field }}
<!--                    <input type="number" name="phone number" placeholder="Eg. 0742491942" class="p-1 mb-2">-->

                    <button type="submit" class="btn btn-dark fw-bold">
                      PAY NOW: KES {{ total_cost_after_discount }}
                    </button>
                </form>

              </div>
            </div>



          </div>


        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
          <div class="order_summary p-2">
            <h3 class="fw-bold">Order Summary</h3>

            {% for item in ordered_items %}
            <div class="products">
              <p class="d-inline">
                <span class="fw-bold"> 1X </span>
               {{ item.product.name }}
              </p>

              <span class="float-end d-inline fw-bold">KES: {{ item.product.price }}</span>
            </div>
            {% endfor %}


            <h6 class="fw-bold text-end mt-4">Sub-Total: {{ order.get_total_cost }}</h6>

           {% if order.coupon %}
               <h6 class="fw-bold text-muted text-end">Coupon: <span class="text-danger">{{ order.discount }}% discount</span></h6>
            {% endif %}
            <hr class="text-danger">
            <h5 class="fw-bold text-end">Total: KES: {{ order.get_total_cost_after_discount }}</h5>
            <hr class="text-danger">

            <p class="text-center fw-bold fst-italic text-muted">Please note that delivery fees is not included!!</p>
          </div>
        </div>
      </div>


      <div class="d-flex">
        <a href="{% url 'payment:payment_options' %}" class="mt-2 btn btn-dark btn-outline-light fw-bold mx-auto">
          <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
          Payment Options
        </a>


       <!-- <a href="order.html" class="mt-2 btn btn-dark btn-outline-danger fw-bold mx-auto flex-end">
          Proceed
          <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
        </a> -->

      </div>

    </div>

{% endblock %}

payment/templates/payment_canceled.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Error Placing an order
{% endblock %}

{% block content %}

<!-- Order Placed Successfully-->

    <div class="mt-2 pt-3 pb-3 container mx-auto alert alert-danger text-center" role="alert">

      <h6 class="text-danger fw-bold">Error Placing an Order</h6>

      <div class="danger-icon mx-auto my-auto justify-content-center">
        <i class="fa fa-times fa-2x text-light pt-2" aria-hidden="true"></i>
      </div>

      <hh7 class="text-danger">

      <span class="text-danger fw-bold">
        Please Contact Anni.Tribe for further clarification.
      </span>
       </hh7>

    </div>

     <div class="text-center">
          <a href="{% url 'products:product_list' %}" class="mt-2 btn btn-dark btn-outline-danger fw-bold text-center">
            Continue Shopping
          </a>
     </div>

{% endblock %}

payment/templates/payment_done.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Successfully placed an order
{% endblock %}

{% block content %}

<!-- Order Placed Successfully-->

    <div class="mt-2 pt-3 pb-3 container mx-auto alert alert-success text-center" role="alert">

      <h6 class="text-success fw-bold">Your Order has been placed successfully</h6> <br>

      <div class="success-icon mx-auto my-auto justify-content-center">
        <i class="fa fa-check fa-2x text-light pt-2" aria-hidden="true"></i>
      </div>
        <br>

      <h7 class="text-success fw-bold">

          <span class="text-success">
            Your Order will be Delivered within the next three business days. <br><br>
              Thank you for Shopping with us.
          </span>
      </h7>

    </div>


     <div class="text-center">
          <a href="{% url 'products:product_list' %}" class="mt-2 btn btn-dark btn-outline-danger fw-bold text-center">
            Continue Shopping
          </a>
     </div>

{% endblock %}

payment/templates/payment_options.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Payment Options
{% endblock %}

{% block content %}

    <!-- Payment Options -->

    <div class="mt-2 pt-3 pb-3 container mx-auto">

      <div class="row gx-4 gy-2">
        <div class="col-lg-6 col-md-6 col-sm-12">
          <div class="row justify-content-center p-2 payment-method">

            <h2 class="fw-bold">Choose Payment Method</h2>

            <div class="form-check col-4" onclick="document.location.href='{% url 'payment:mpesa_payment' %}'">
              <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
              <div class="form-check-label card border-0" for="flexRadioDefault1">
                <img src="{% static 'images/mpesa.png' %}" class="card-img w-70">
              </div>
            </div>


            <div class="form-check col-4" onclick="document.location.href='{% url 'payment:card_payment' %}'">
              <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
              <div class="form-check-label card border-0" for="flexRadioDefault2">
                <img src="{% static 'images/card.png' %}" class="card-img w-70">
              </div>
            </div>


            <div class="form-check col-4" onclick="document.location.href='order_success.html'">
              <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3">
              <div class="form-check-label card border-0" for="flexRadioDefault3">
                <img src="{% static 'images/cash_on_delivery.png' %}" class="card-img w-70">
              </div>
            </div>

          </div>

        </div>

        <div class="col-lg-6 col-md-6 col-sm-12">

          <div class="order_summary p-3">
            <h3 class="fw-bold">Order Summary</h3>


            {% for item in ordered_items %}
            <div class="products">
              <p class="d-inline">
                <span class="fw-bold"> 1X </span>
               {{ item.product.name }}
              </p>

              <span class="float-end d-inline fw-bold">KES: {{ item.product.price }}</span>
            </div>
            {% endfor %}


            <h6 class="fw-bold text-end mt-4">Sub-Total: {{ order.get_total_cost }}</h6>

           {% if order.coupon %}
               <h6 class="fw-bold text-muted text-end">Coupon: <span class="text-danger">{{ order.discount }}% discount</span></h6>
            {% endif %}
            <hr class="text-danger">
            <h5 class="fw-bold text-end">Total: KES: {{ order.get_total_cost_after_discount }}</h5>
            <hr class="text-danger">

            <p class="text-center fw-bold fst-italic text-muted">Please not that delivery fees is not included!!</p>

          </div>
        </div>
      </div>


      <div class="d-flex">
        <a href="checkout.html" class="mt-2 btn btn-dark btn-outline-light fw-bold mx-auto">
          <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
          Shipping Address
        </a>


       <!-- <a href="order.html" class="mt-2 btn btn-dark btn-outline-danger fw-bold mx-auto flex-end">
          Proceed
          <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
        </a> -->

      </div>

    </div>

{% endblock %}