account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    # registration view
    path('register/', views.register, name='register'),

    # verify
    path('verify/', views.verify_code, name='verify'),

    # login and logout urls
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # dashboard
    path('dashboard/', views.dashboard, name='dashboard'),

    # side bar dash
    path('side_dash/', views.side_dash, name='side_dash'),

    # change password urls
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # reset password urls
    path('password_reset/', views.PasswordResetView.as_view(),
         name='password_reset', ),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('account/reset/done', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

annietribe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),

                  # orders urls
                  path('payment/', include('payment.urls', namespace='payment')),

                  # orders urls
                  path('orders/', include('orders.urls', namespace='orders')),

                  # coupon urls
                  path('coupons/', include('coupons.urls', namespace='coupons')),

                  # cart urls
                  path('cart/', include('cart.urls', namespace='cart')),

                  # wishlist urls
                  path('wishlist/', include('wishlist.urls', namespace='wishlist')),

                  # account
                  path('account/', include('account.urls', namespace='account')),

                  # products
                  path('', include('products.urls', namespace='products')),

                  # ckeditor
                  path('ckeditor/', include('ckeditor_uploader.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name="order_list"),

    path('create/', views.order_create, name='order_create'),
]

wishlist/urls.py
from django.urls import path, include
from . import views

app_name = 'wishlist'

urlpatterns = [
    path("", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="add_to_wishlist"),
]

orders/models.py
from decimal import Decimal
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator, \
    MaxValueValidator
from django.db import models

from products.models import Product
from coupons.models import Coupon
from account.models import User


# Create your models here.
class Order(models.Model):
    order_status_choices = (
        ('Pending', 'Pending'),
        ('En_route', 'En_route'),
        ('Delivered', 'Delivered'),
        ('Canceled', 'Canceled'),
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = PhoneNumberField()
    county = models.CharField(max_length=100)
    town = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    order_status = models.CharField(max_length=10,
                                    choices=order_status_choices,
                                    default='Pending', )
    coupon = models.ForeignKey(Coupon,
                               related_name='orders',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL)
    sub_total = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    total = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    discount = models.IntegerField(default=0,
                                   validators=[MinValueValidator(0),
                                               MaxValueValidator(100)])
    braintree_id = models.CharField(max_length=150, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost

    def get_total_cost_after_discount(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - round(total_cost * (self.discount / Decimal(100)), 2)


class OrderItem(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             null=True, blank=True)
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)

    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['county', 'town',
                  'address', 'postal_code']

orders/views.py
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart

# Create your views here.


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        order_form = OrderCreateForm(request.POST)

        if order_form.is_valid():
            order = order_form.save(commit=False)
            user = request.user

            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount

            order.sub_total = Decimal(cart.get_total_price())
            order.total = Decimal(cart.get_total_price_after_discount())

            order.first_name = user.first_name
            order.last_name = user.last_name
            order.email = user.email
            order.phone_number = user.phone

            order.save()

            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'])

            # clear cart
            cart.clear()

            # set the order in the session
            request.session['order_id'] = order.id

            return redirect(reverse('payment:payment_options'))
    else:
        order_form = OrderCreateForm()
    return render(request, 'create.html', {'cart': cart,
                                           'order_form': order_form, })


@login_required
def order_list(request):
    orders = Order.objects.all()
    ordered_items = OrderItem.objects.filter(user=request.user.pk)
    return render(request, 'orders.html',
                  {'orders': orders,
                   'ordered_items': ordered_items})

orders/templates/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Create Order
{% endblock %}

{% block content %}
<style>
label{
  font-weight: bold;
  }

.help-block{
color: red;
}

input{
    width: 100%;
    padding: 0.2rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }
</style>
    <!-- Pick Up and Delivery Address -->
    <form method="post" action="" class="mt-3 delivery-address pt-3  pb-3 container mx-auto">
      <h2 class="fw-bold">Delivery Address</h2>
      <div class="row justify-content-center">

        <div class="col-lg-6 col-md-6">
          {{ order_form.county|as_crispy_field }}
        </div>

        <div class="col-lg-6 col-md-6">
          {{ order_form.town|as_crispy_field }}
        </div>

        <div class="col-lg-6 col-md-6">
          {{ order_form.address|as_crispy_field }}
        </div>

        <div class="col-lg-6 col-md-6">
          {{ order_form.postal_code|as_crispy_field }}
        </div>

      </div>

      <div class="d-flex">
        <a href="{% url 'cart:cart_detail' %}" class="mt-2 btn btn-dark btn-outline-light fw-bold mx-auto">
          <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
        Back to Cart
      </a>


      <button type="submit" class="mt-2 btn btn-dark btn-outline-danger fw-bold mx-auto flex-end">
        Proceed To Payment
        <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
      </button>
      <!--
        <input type="submit" name="delivery-address" value="Proceed To Payment" class="w-25 mt-2 btn btn-dark btn-outline-danger fw-bold mx-auto float-end">
        -->
      </div>
      {% csrf_token %}
    </form>

{% endblock %}

orders/templates/orders.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Your Orders
{% endblock %}

{% block content %}
    <div class="account-cont mt-2">
      <div role="tabpanel row border">
        <!-- List group -->
        <div class="row gx-4">
          <div class="col-4">
            <div class="list-group list-group-cont" id="myList" role="tablist">

              <a class="list-group-item list-group-item-action fw-bold" data-bs-toggle="{% url 'account:dashboard' %}" href="{% url 'account:dashboard' %}" role="tab">
                <i class="fa fa-address-card fs-3" aria-hidden="true"> </i>
                Account Details
              </a>

              <a class="list-group-item  active list-group-item-action fw-bold" data-bs-toggle="{% url 'orders:order_list' %}" href="{% url 'orders:order_list' %}" role="tab">
                <i class="fa fa-shopping-bag fs-3" aria-hidden="true"> </i>
                Orders</a>

              <a class="list-group-item list-group-item-action fw-bold" data-bs-toggle="{% url 'wishlist:wishlist' %}" href="{% url 'wishlist:wishlist' %}" role="tab">
                <i class="fa fa-heart fs-3" aria-hidden="true"> </i>
                Wish List
              </a>

<!--              <a class="list-group-item list-group-item-action fw-bold" data-bs-toggle="recently-viewed.html" href="recently-viewed.html" role="tab">-->
<!--                <i class="fa fa-history fs-3" aria-hidden="true"> </i>-->
<!--                Recently Viewed Items-->
<!--              </a>-->

              <a class="list-group-item list-group-item-action fw-bold pt-2" data-bs-toggle="{% url 'account:password_change' %}" href="{% url 'account:password_change' %}" role="tab">
                <i class="fa fa-unlock fs-3" aria-hidden="true"> </i>
                Reset Password
              </a>

            </div>
          </div>

          <div class="col-8">
            <!-- Tab panes -->
            <div class="tab-content tab-cont p-2">

              <div class="tab-pane fade active show p-2" id="orders" role="tabpanel">
                <h4 class="fw-bolder list-group-item border-start-0 border-top-0 border-end-0">Order History</h4>

                {% if ordered_items %}
                  <div class="table-responsive mt-2">
                  <table class="table table-dark table-striped table-hover border-danger">
                    <thead>
                      <tr>
                        <th scope="col" class="align-top">Product Image</th>
                        <th scope="col" class="align-top">Product Name</th>
                        <th scope="col" class="align-top"> Order ID</th>
                        <th scope="col" class="align-top">Payment Status</th>
                        <th scope="col" class="align-top">Order Status</th>
                        <th scope="col" class="align-top">Price</th>
                      </tr>
                    </thead>
                    <tbody>
                      <!-- Single Order -->
                        {% for order in ordered_items %}
                            <tr class="align-middle">
                              <th scope="row">
                                <a href="{{ order.product.get_absolute_url }}">
                                  <!--Order image -->
                                  <img src="{{ order.product.photo.url }}" class="cart-img">
                                </a>
                              </th>

                              <td>
                                <!-- Order Name -->
                                <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-wrap fw-bold text-light">
                                    {{order.product.name}}
                                </a>
                              </td>

                              <td>
                                <!-- Order ID -->
                                {{order.id}}
                              </td>

                              {% if order.order.paid == True %}
                                <td class="fw-bold text-success">
                                  <!--  Payment Status -->
                                  PAID
                                </td>
                              {% else %}
                                <td class="fw-bold text-danger">
                                  <!--  Payment Status -->
                                  NOT PAID
                                </td>
                              {% endif %}

                              {% if order.order.order_status == Pending %}
                                <td class="fw-bold text-warning">
                                  <!-- Order Status -->
                                  {{order.order.order_status}}
                                </td>
                              {% elif order.order.order_status == En_route %}
                                <td class="fw-bold text-primary">
                                  <!-- Order Status -->
                                  {{order.order.order_status}}
                                </td>
                              {% elif order.order.order_status == Delivered %}
                                <td class="fw-bold text-success">
                                  <!-- Order Status -->
                                  {{order.order.order_status}}
                                </td>
                              {% else%}
                                <td class="fw-bold text-danger">
                                  <!-- Order Status -->
                                  {{order.order.order_status}}
                                </td>
                              {% endif %}

                              <td>
                                <!-- Unit Price -->
                                <h6 class="fw-bold d-flex"><span>Ksh: </span> {{ order.product.price }} </h6>
                              </td>

                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
                {% else %}
                  <h6 class="fw-bold">You have not made any orders yet. Continue shopping with annie.tribe</h6>
                {% endif %}
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}