account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    # registration view
    path('register/', views.register, name='register'),

    # verify
    path('verify/', views.verify_code, name='verify'),

    # login and logout urls
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # dashboard
    path('dashboard/', views.dashboard, name='dashboard'),

    # side bar dash
    path('side_dash/', views.side_dash, name='side_dash'),

    # change password urls
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # reset password urls
    path('password_reset/', views.PasswordResetView.as_view(),
         name='password_reset', ),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('account/reset/done', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

annietribe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),

                  # orders urls
                  path('payment/', include('payment.urls', namespace='payment')),

                  # orders urls
                  path('orders/', include('orders.urls', namespace='orders')),

                  # coupon urls
                  path('coupons/', include('coupons.urls', namespace='coupons')),

                  # cart urls
                  path('cart/', include('cart.urls', namespace='cart')),

                  # wishlist urls
                  path('wishlist/', include('wishlist.urls', namespace='wishlist')),

                  # account
                  path('account/', include('account.urls', namespace='account')),

                  # products
                  path('', include('products.urls', namespace='products')),

                  # ckeditor
                  path('ckeditor/', include('ckeditor_uploader.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name="order_list"),

    path('create/', views.order_create, name='order_create'),
]

wishlist/urls.py
from django.urls import path, include
from . import views

app_name = 'wishlist'

urlpatterns = [
    path("", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="add_to_wishlist"),
]

wishlist/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from products.models import Product


@login_required
def wishlist(request):
    user = request.user
    products = Product.objects.filter(users_wishlist=request.user)
    return render(request, 'wishlist_detail.html',
                  {"wishlist": products,
                   'user': user})


@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user.id)
        messages.success(request, product.name + " has been removed from your WishList")
    else:
        product.users_wishlist.add(request.user.id)
        messages.success(request, "Added " + product.name + " to your WishList")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

wishlist/templates/wishlist_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    My Wishlist
{% endblock %}

{% block content %}

    <div class="account-cont mt-2">
      <div role="tabpanel row border">
        <!-- List group -->
        <div class="row gx-4">

          <div class="col-4">

            <div class="list-group list-group-cont" id="myList" role="tablist">

              <a class="list-group-item list-group-item-action fw-bold" data-bs-toggle="{% url 'account:dashboard' %}" href="{% url 'account:dashboard' %}" role="tab">
                <i class="fa fa-address-card fs-3" aria-hidden="true"> </i>
                Account Details
              </a>

              <a class="list-group-item list-group-item-action fw-bold" data-bs-toggle="{% url 'orders:order_list' %}" href="{% url 'orders:order_list' %}" role="tab">
                <i class="fa fa-shopping-bag fs-3" aria-hidden="true"> </i>
                Orders</a>

              <a class="list-group-item active list-group-item-action fw-bold" data-bs-toggle="{% url 'wishlist:wishlist' %}" href="{% url 'wishlist:wishlist' %}" role="tab">
                <i class="fa fa-heart fs-3" aria-hidden="true"> </i>
                Wish List
              </a>

<!--              <a class="list-group-item list-group-item-action fw-bold" data-bs-toggle="recently-viewed.html" href="recently-viewed.html" role="tab">-->
<!--                <i class="fa fa-history fs-3" aria-hidden="true"> </i>-->
<!--                Recently Viewed Items-->
<!--              </a>-->

              <a class="list-group-item list-group-item-action fw-bold pt-2" data-bs-toggle="{% url 'account:password_change' %}" href="{% url 'account:password_change' %}" role="tab">
                <i class="fa fa-unlock fs-3" aria-hidden="true"> </i>
                Reset Password
              </a>

            </div>

          </div>

          <div class="col-8">
            <!-- Tab panes -->
            <div class="tab-content tab-cont p-2">

              <div class="tab-pane fade active show p-2" id="wishlist" role="tabpanel">
                <h4 class="fw-bolder list-group-item border-start-0 border-top-0 border-end-0">
                  Saved Items
                  ({% with total_items=wishlist|length %}
                    {% if total_items > 0 %}
                      {{ total_items }}
                    {% else %}
                        0
                    {% endif %}
                  {% endwith %})
                </h4>

                <div class="table-responsive">
                  <!-- Single saved Item  -->
                  <table class="table border-danger">
                    <tbody>

                      <!-- Single Wishlist -->
                      {% if wishlist %}
                        {% for product in wishlist %}
                          <tr class="align-middle">
                            <th scope="row">
                              <a href="{{ product.get_absolute_url }}">
                                <!--Saved image -->
                                <img src="{{ product.photo.url }}" class="saved-item-img">
                              </a>
                            </th>

                            <td>
                              <!-- Saved Name -->
                              <a href="{{ product.get_absolute_url }}" class="text-decoration-none fw-bold text-dark">
                                {{product.name}}
                              </a>

                              <br>

                              <!-- Unit Price -->
                              <h6 class="fw-bold mt-3"><span>Ksh: </span> {{product.price}}</h6>
                            </td>

                            <td>
                              <a class="btn btn-md btn-light btn-outline-dark fw-bold text-nowrap" href="">
                                Buy Now
                              </a>

                              <br>
                              <a href="{% url 'wishlist:add_to_wishlist' product.id  %}" class="btn btn-md btn-outline-dark btn-danger mt-1 fw-bold text-light" role="button" aria-disabled="true">
                                Remove
                              </a>
                            </td>
                          </tr>
                        {% endfor %}
                      {% else %}
                        <h6 class="fw-bold">You have not saved any items yet. Continue shopping with annie.tribe</h6>
                      {% endif %}

                    </tbody>
                  </table>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}