annietribe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),

                  # orders urls
                  path('payment/', include('payment.urls', namespace='payment')),

                  # orders urls
                  path('orders/', include('orders.urls', namespace='orders')),

                  # coupon urls
                  path('coupons/', include('coupons.urls', namespace='coupons')),

                  # cart urls
                  path('cart/', include('cart.urls', namespace='cart')),

                  # wishlist urls
                  path('wishlist/', include('wishlist.urls', namespace='wishlist')),

                  # account
                  path('account/', include('account.urls', namespace='account')),

                  # products
                  path('', include('products.urls', namespace='products')),

                  # ckeditor
                  path('ckeditor/', include('ckeditor_uploader.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_list, name="order_list"),

    path('create/', views.order_create, name='order_create'),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [
    # newsletter urls
    path('subscribe', views.subscribe_view, name='subscribe'),

    path('success/', views.subscribe_success_view, name='subscribe_success'),

    path('fail/', views.subscribe_fail_view, name='subscribe_fail'),

    path('unsubscribe/', views.unsubscribe_view, name='unsubscribe'),

    path('unsubscribe/success/', views.unsubscribe_success_view, name='unsubscribe_success'),

    path('unsubscribe/fail/', views.unsubscribe_fail_view, name='unsubscribe_fail'),

    # index page
    path('', views.index, name='index'),

    path('contact/', views.contact, name='contact'),

    # list of all products
    path('products/', views.product_list, name='product_list'),

    path('search/', views.search, name='search'),

    # list of products in a given category
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),

    # product detail
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = int(1)
    """forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )"""
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from account.decorators import verification_required


@verification_required
@login_required
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 # quantity=cd['quantity'],
                 # override_quantity=cd['override']
                 )
        product.available = False
        product.save()
    return redirect('cart:cart_detail')


@verification_required
@login_required
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    product.available = True
    product.save()
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    """for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })"""
    return render(request, 'cart_detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

cart/templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    My Cart
{% endblock %}

{% block content %}
<style>
label{
  font-weight: bold;
  }

.help-block{
color: red;
}

input{
    width: 100%;
    padding: 0.2rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border-radius: 0.25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
  }
</style>
    <div class="cart-cont table-responsive mt-2">
      <table class="table table-dark table-hover border-danger">
        <thead>
          <tr>
            <th scope="col">Product Image</th>
            <th scope="col">Product</th>
            <th scope="col">Quantity</th>
            <th scope="col">Remove</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Sub-Total</th>
          </tr>
        </thead>
        <tbody>

          {% for item in cart %}
            {% with product=item.product %}
              <!-- Single Order -->
              <tr class="align-middle">
                <th scope="row">
                  <a href="{{ product.get_absolute_url }}">
                    <!-- product image -->
                    <img src="{{ product.photo.url }}" class="cart-img">
                  </a>
                </th>

                <td>
                  <!-- Product Name -->
                  <a href="{{ product.get_absolute_url }}" class="text-decoration-none cart-product-title">
                    {{product.name}}
                  </a>
                </td>

                <td>
                  <!-- Product Quantity -->
                  <!--
                  <form method="" action="" class="d-flex">
                    <input min="0" max="10" name="quantity" value="1" type="number">
                    <input type="submit" name="Update" value="Update" class="fw-bold btn btn-sm btn-light btn-outline-danger ms-2">
                  </form>
                  -->
                    {{ item.quantity }}
                </td>

                <td>
                  <!-- Remove Product -->
                  <form action="{% url 'cart:cart_remove' product.id %}" method="post" class="d-flex">
                    <button type="submit" name="Remove" class="fw-bold delete-btn btn btn-outline-0 btn-sm  ms-2">
                      <i class="fa fa-trash-o fs-4" aria-hidden="true"></i>
                    </button>
                      {% csrf_token %}
                  </form>
                </td>

                <td>
                  <!-- Unit Price -->
                  <h6 class="fw-bold d-flex"><span>Ksh: </span> {{ item.price }}</h6>
                </td>

                <td>
                  <!-- Sub Total -->
                  <h6 class="fw-bold d-flex"><span>Ksh: </span> {{ item.total_price }}</h6>
                </td>
              </tr>
            {% endwith %}
          {% endfor %}

        </tbody>
      </table>
    </div>

    <div class="row justify-content-center container-fluid mt-3">

      <div class="col-lg-4 col-md-4 col-sm-8  cart-total p-3">
        {% if cart.coupon %}
          <h3 class="fw-bold text-center">Order Total Cost</h3>
          <hr>

          <h6 class="fw-bold">Sub-Total
            <span class="float-end"> Ksh. {{ cart.get_total_price|floatformat:2}} </span>
          </h6>

          <h6 class="fw-bold text-danger">
            "{{ cart.coupon.code }}"
            ({{ cart.coupon.discount }}% off)

            <span class="float-end"> - Ksh. {{ cart.get_discount|floatformat:2 }} </span>
          </h6>
        {% endif %}

        <hr class="text-danger">
        <h6 class="fw-bold">
          Total:
          <span class="float-end"> Ksh. {{ cart.get_total_price_after_discount|floatformat:2 }} </span>
        </h6>
        <hr class="text-danger">

        <form class="text-center" action="{% url 'coupons:apply' %}" method="post">
          {{ coupon_apply_form.code|as_crispy_field }}
          <br>
          <button type="submit" name="Coupon" class="btn btn-dark btn-outline-danger fw-bold mt-1 px-4 w-100">
            <i class="fa fa-gift" aria-hidden="true"> Apply Coupon</i>
          </button>
          {% csrf_token %}
        </form>

        <p class="text-center fw-bold mt-2 fst-italic text-muted alert alert-danger" role="alert">Please not that delivery fees is not billed!!</p>
      </div>

    </div>

    <a href="{% url 'products:product_list' %}" class="btn btn-dark btn-outline-danger fw-bold mt-3">
      <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
      Continue Shopping
    </a>

    <a href="{% url 'orders:order_create' %}" class="btn btn-dark btn-outline-danger fw-bold mt-3 float-end">
      Proceed to Checkout
      <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
    </a>
{% endblock %}